# Generated by Django 6.0.3 on 2026-03-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsuarioModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CarnetIdentidad",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("nombre", models.CharField(blank=True, max_length=45, null=True)),
                ("apellido", models.CharField(blank=True, max_length=45, null=True)),
                ("password", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "correoElectronico",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("direccion", models.CharField(blank=True, max_length=45, null=True)),
                ("telefono", models.CharField(blank=True, max_length=45, null=True)),
                ("fechaNacimiento", models.DateField(blank=True, null=True)),
                ("rol", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
