# Generated by Django 6.0.3 on 2026-03-19 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usuariomodel",
            table="usuarios",
        ),
    ]
